Times100<-function(Data){
  Data$PCT_OBESE <- Data$PCT_OBESE*100
  Data$PCT_OVERWE <- Data$PCT_OVERWE*100
  Data$PCT_OVER_1 <- Data$PCT_OVER_1*100
  
  Data$PER_FREE_L <- Data$PER_FREE_L*100
  Data$PER_REDUCE <- Data$PER_REDUCE*100
  Data$PER_LUNCH<- Data$PER_FREE_L+ Data$PER_REDUCE
  
  Data$SP.FSV.INDEX<-Data$COUNT.FF/
    (Data$COUNT.FF+Data$COUNT.NOT.FF)*100
  Data$SP.FST.INDEX<-Data$COUNT.GROCERY/
    (Data$COUNT.GROCERY+Data$COUNT.SUP)*100
  
  return(Data)
}
Data_10_12.DISTRICT.TOTAL<-Times100(Data_10_12.DISTRICT.TOTAL)
Data_10_12.ELEMENTARY<-Times100(Data_10_12.ELEMENTARY)
Data_10_12.MIDDLE.HIGH<-Times100(Data_10_12.MIDDLE.HIGH)
